### ISSUE TITLE
Rebase current Kyzer branch, and redo changes

### ISSUE THREAD

**Issue by Frontear** [Frontear/osuKyzer#1]
Currently, peppy has added a new branch called "release". While we will remain on master, many framework changes have occured, which are currently breaking our code. We plan to completely remove and rebase our changes, and then redo everything, from scratch.

**Comment by jorolf** [comment]
What have I found here 👀

**Comment by Frontear** [comment]
I wonder :>

**Comment by Kontorted** [comment]
Closing until lazer initial release.
